return {
    {
        'catppuccin/nvim',
        name = 'catppuccin',
        enabled = true,
        priority = 100,
        init = function()
            vim.cmd.colorscheme('catppuccin')
        end,
        opts = {
            flavour = 'mocha',
            transparent_background = false,
            show_end_of_buffer = false,
            term_colors = true,
            no_italic = false,
            no_bold = false,
            styles = {
                comments = { 'italic' },
                conditionals = {},
                loops = {},
                functions = {},
                keywords = {},
                strings = {},
                variables = {},
                numbers = {},
                booleans = {},
                properties = {},
                types = {},
                operators = {},
            },
            color_overrides = {},
            integrations = {
                alpha = true,
                leap = true,
                cmp = true,
                gitsigns = true,
                nvimtree = true,
                fidget = true,
                telescope = true,
                notify = true,
                fzf = true,
                harpoon = true,
                markdown = true,
                noice = true,
                treesitter = true,
                symbols_outline = true,
                lsp_trouble = true,
                which_key = true,
                native_lsp = {
                    enabled = true,
                },
                indent_blankline = {
                    enabled = true,
                    scope_color = '',
                    colored_indent_levels = false,
                },
                mason = true,
                neogit = true,
                dap = true,
                dap_ui = true,
            },
        },
    },
}
